[package]
name = "oh-my-crab"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
dirs = "5.0.1"
phf = { version = "0.11.3", features = ["macros"] }
